import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  // https://docusaurus.io/docs/sidebar
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: "Tutorial - Basics",

      link: {
        type: "generated-index",
        description: "5 minutes to learn the most important Docusaurus concepts.",
        keywords: ['tutorial'],
        title: 'wow',
      },
      items: [
        'tutorial-basics/create-a-page', 
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/markdown-features',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/congratulations',
      ],
    },
    {
      type: 'category',
      label: "Tutorial - Extras",
      link: {
        type: "generated-index",
      },
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
    {
      type: 'category',
      label: 'Prompting',
      link: {
        type: 'doc',
        id: 'prompting/prompting_index',
      },
      items: [
        'prompting/chain-of-thought',
      ],
    },
    {
      type: 'category',
      label: 'Vectors / Embeddings',
      link: {
        type: 'generated-index',
      },
      items: [
        'vectors_embeddings/vector_embeddings',
        'vectors_embeddings/word-2-vec'
      ],
    },
    {
      type: 'category',
      label: 'Quantization',
      link: {
        type: 'doc',
        id: 'quantization/quantization_index',
      },
      items: [
        'quantization/gptq',
        'quantization/spqr',
        'quantization/bitsandbytes',
        'quantization/awq',
        'quantization/aqlm',
        'quantization/quanto',
        'quantization/smoothquant',
        'quantization/kvquant',
        'quantization/one_bit',
        'quantization/eetq',
        'quantization/hqq',
        'quantization/quip',
        'quantization/squeeze',
        'quantization/mixture_of_quantization',
        'quantization/marlin',
        'quantization/llama_cpp',
        'quantization/omniquant',
        'quantization/rptq',
        'quantization/obc',
        'quantization/athena',
        'quantization/leanquant',
        'quantization/fp8',
      ],
    },
    {
      type: 'category',
      label: 'Training',
      link: {
        type: 'generated-index',
      },
      items: [
        'training/ray',
        {
          type: 'category',
          label: 'Reinforcement Learning',
          link: {
            type: 'generated-index',
          },
          items: [
            'training/reinforcement-learning/rlhf',
            'training/reinforcement-learning/a3c',
            'training/reinforcement-learning/align-prop',
            'training/reinforcement-learning/cpo',
            'training/reinforcement-learning/ddpg',
            'training/reinforcement-learning/ddpo',
            'training/reinforcement-learning/deep-q-learning',
            'training/reinforcement-learning/dno',
            'training/reinforcement-learning/dpo',
            'training/reinforcement-learning/dsac',
            'training/reinforcement-learning/kto',
            'training/reinforcement-learning/monte-carlo',
            'training/reinforcement-learning/orpo',
            'training/reinforcement-learning/ppo',
            'training/reinforcement-learning/q-learning',
            'training/reinforcement-learning/rloo',
            'training/reinforcement-learning/sac',
            'training/reinforcement-learning/sarsa',
            'training/reinforcement-learning/td-learning',
            'training/reinforcement-learning/td3',
            'training/reinforcement-learning/trpo',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Serving',
      link: {
        type: 'generated-index',
      },
      items: [
        'serving/ray',
        {
          type: 'category',
          label: 'Decoding',
          link: {
            type: 'generated-index',
          },
          items: [
            'serving/decoding/medusa',
            'serving/decoding/speculative'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Attention',
      link: {
        type: 'generated-index',
      },
      items: [
        'attention/self-attention',
      ],
    },
    {
      type: 'category',
      label: 'Adapters',
      link: {
        type: 'generated-index',
      },
      items: [
        'adapters/lora',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      link: {
        type: 'generated-index',
      },
      items: [
        'research/some-research',
      ],
    },
    {
      type: 'category',
      label: 'Safety',
      link: {
        type: 'generated-index',
      },
      items: [
        'safety/safety',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation',
      link: {
        type: 'generated-index',
      },
      items: [
        'evaluation/truthfulness',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'generated-index',
      },
      items: [
        'ops/llmops',
        'ops/pezzo',
        'ops/agenta',
      ],
    },
    {
      type: 'category',
      label: 'Extras',
      link: {
        type: 'generated-index',
      },
      items: [
        'extras/semantic-router',
      ],
    },
  ],
  
};

export default sidebars;
